version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: challenge-postgres
    environment:
      POSTGRES_DB: challenge_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xtra
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - challenge-network

  app:
    build: .
    container_name: challenge-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/challenge_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: xtra
    depends_on:
      - postgres
    networks:
      - challenge-network

volumes:
  postgres_data:

networks:
  challenge-network:
    driver: bridge