spring:
  application:
    name: backend-challenge

  datasource:
    url: jdbc:postgresql://localhost:5432/challenge_db
    username: postgres
    password: xtra
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  cache:
    type: simple

external:
  percentage:
    url: "https://mock-external-service.com/percentage"

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
